name: Verify

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew --no-build-cache ktlintCheck :plugin:ktlintCheck

  tests:
    continue-on-error: true
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - run: ./gradlew :example:dockerPush :example:dockerBuildxPush
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          IMAGE_VERSION: ${{ github.run_id }}-${{ github.run_number }}

  publication:
    runs-on: ubuntu-latest
    name: Publication
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - run: ./gradlew :plugin:publishAllPublicationsToTestRepository